// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUsers = "users"

// Users mapped from table <users>
type Users struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name      string     `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Email     string     `gorm:"column:email;type:varchar(100);not null;uniqueIndex:email,priority:1" json:"email"`
	Age       *int32     `gorm:"column:age;type:int" json:"age"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Users's table name
func (*Users) TableName() string {
	return TableNameUsers
}
